### ISSUE TITLE
Point cloud decoding failed error on empty Pointcloud

### ISSUE THREAD

**Issue by gilduz** [foxglove/studio#2186]
**Description**
Pointcloud data with empty datafield generate error "Point cloud decoding failed"

- Version: Foxglove Studio v0.22.1
- OS: Ubuntu 18.04

**Steps To Reproduce**

Create a Pointcloud2 msg with the following content:

```
header: 
  seq: 1635729
  stamp: 
    secs: 1637311582
    nsecs: 506327942
  frame_id: "world"
height: 1
width: 0
fields: 
  - 
    name: "x"
    offset: 0
    datatype: 7
    count: 1
  - 
    name: "y"
    offset: 4
    datatype: 7
    count: 1
  - 
    name: "z"
    offset: 8
    datatype: 7
    count: 1
is_bigendian: False
point_step: 16
row_step: 0
data: []
is_dense: False
```
Got the following error on every received message

![image](https://user-images.githubusercontent.com/1778733/142597739-2df92c1a-08f0-41a9-840e-1ca6b28eedd1.png)

**Expected Behavior**
Reproduce Rviz behaviour: nothing displayed since pointcloud is empty but without errors

**Actual Behavior**
"Point cloud decoding failed" error displayed on every message received
