### ISSUE TITLE
load remote bag from url state fails

### ISSUE THREAD

**Issue by frapit** [foxglove/studio#2299]
**Description**
The recently introduced feature (https://github.com/foxglove/studio/pull/2171, thank you @foxymiles) to represent the current state (bag+layout+time) in the url misbehaves in my first tests. I always get redirected to the welcome scenario at 
`https://example.org/foxglove/?ds=ros1-remote-bagfile&ds.url=https%3A%2F%2Fstorage.googleapis.com%2Ffoxglove-public-assets%2Fdemo.bag&layoutId=bff4eafa-77d2-4c0f-87a1-a19731fa887b&time=2017-03-22T02%3A26%3A20.202843112Z` instead of the desired remote bag. 

I use the docker container for a self hosted version and the only adjustion I made is to host at a subpath `/foxglove`.

- Version: 0.23.0, self hosted
- OS: ubuntu20.04

**Steps To Reproduce**
In the start up view, load a new remote bag via the panel -> bag loads successfully -> url gets replaced.
Then copy that url and paste it into a new chrome session -> bag and view shows up for a second but then the welcome layout + bag loads and overwrite the state. 

Do I use it wrong or what could be the issue here?
Thanks

**Comment by frapit** [comment]
Sure, I use the Dockerfile from the repo. I changed the `publicPath` property in `web/webpack.config.ts` to be `publicPath: "/foxglove/"` I build the container and launch using the following docker-compose.yml:

```
version: '3.6'
services:
    foxglove:
        image: foxglove:latest
        network_mode: host
        restart: unless-stopped
        volumes:
            - ./Caddyfile:/src/Caddyfile:ro
        command: ["caddy", "run"]
volumes:
  Caddyfile:
```

with the `Caddyfile` being:
```
:8080 {
	handle /foxglove* {
		root * ./
		try_files {path} /index.html
		file_server
	}
```
and some additional routing with traefik.

The same thing happens for local deployment and also the publicly hosted demo at [https://studio.foxglove.dev/](https://studio.foxglove.dev/) as well so I am not sure if it is related to the docker setup.
