### ISSUE TITLE
Map panel breaks if robot loses GPS fix

### ISSUE THREAD

**Issue by wojtekbacza-coco** [foxglove/studio#4763]
**Description**
If robot loses GPS fix at any point in time, the map panel will go blank when it loads this data point, making us unable to plot any robot path where GPS was lost even for 1 second.
Here is an example `sensor_msgs/NavSatFix` message that causes the problem:
```yaml
header: 
  seq: 1
  stamp: 
    secs: 1667575031
    nsecs: 618148088
  frame_id: "/gps"
status: 
  status: -1
  service: 1
latitude: nan
longitude: nan
altitude: nan
position_covariance: [20.25, 0.0, 0.0, 0.0, 20.25, 0.0, 0.0, 0.0, 81.0]
position_covariance_type: 1
```
This message is coming from [https://wiki.ros.org/nmea_navsat_driver](https://wiki.ros.org/nmea_navsat_driver) GPS driver. When we filtered out all messages with `header.status.service==-1` then the rest of the path got loaded and displayed correctly.

- Version: 1.30.0
- OS: Ubuntu (both in studio and web)
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): Bag file
- ROS distro (if applicable): noetic

**Steps To Reproduce**

Load any bag with aforementioned message, the Map panel will go blank.
Attached are 2 bags, [map_panel_not_working.zip](https://github.com/foxglove/studio/files/9942714/map_panel_not_working.zip) - shows short GPS path that causes map panel not to load, [no_fix_messages_filtered.zip](https://github.com/foxglove/studio/files/9942715/no_fix_messages_filtered.zip) - same path, but with messages with `header.status.service==-1` filtered out - on this bag the panel loads correctly.

**Expected Behavior**
Path is displayed correctly, ignoring messages without GPS fix.

**Actual Behavior**
Map panel goes blank
