### ISSUE TITLE
Ros2 MarkerArray with not timestamp does not show

### ISSUE THREAD

**Issue by tonynajjar** [foxglove/studio#6991]
**Description**

- Version:1.72.0
- Platform: desktop
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): foxglove bridge ROS2

**Steps To Reproduce**

I am publishing a MarkerArray which I can visualize in Rviz but not in Foxglove:

```
markers:
- header:
    stamp:
      sec: 0
      nanosec: 0
    frame_id: base_link
  ns: collision_points
  id: 0
  type: 8
  action: 0
  pose:
    position:
      x: 0.0
      y: 0.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  scale:
    x: 0.1
    y: 0.1
    z: 0.0
  color:
    r: 1.0
    g: 0.0
    b: 0.0
    a: 1.0
  lifetime:
    sec: 2
    nanosec: 0
  frame_locked: false
  points:
  - x: -2.999214073461749
    y: 0.5856084967843912
    z: 0.0
  - x: -2.999214073461749
    y: 0.5856084967843912
    z: 0.0
  - x: -2.999214073461749
    y: 0.5856084967843912
    z: 0.0
  - x: -2.999214073461749
    y: 0.5856084967843912
    z: 0.0
  colors: []
  texture_resource: ''
  texture:
    header:
      stamp:
        sec: 0
        nanosec: 0
      frame_id: ''
    format: ''
    data: []
  uv_coordinates: []
  text: ''
  mesh_resource: ''
  mesh_file:
    filename: ''
    data: []
  mesh_use_embedded_materials: false
```

I noticed that when the message is given a recent timestamp, it does appear in foxglove however it breaks in rviz for reasons I don't know. I would expect foxglove to behave like Rviz when not given a timestamp as described [here](http://wiki.ros.org/rviz/DisplayTypes/Marker#:~:text=Note%20that%20the,the%20current%20time.)
